Repository sulu/SuluHeadlessBundle, pull requests merged in 2020-08, with the labels that each got.

#45 Add "single_category_selection" Content Type Resolver
  Content/ContentTypeResolver/SingleCategorySelectionResolver.php
  Resources/config/content-type-resolvers.xml
  Tests/Unit/Content/ContentTypeResolver/SingleCategorySelectionResolverTest.php
Labels: Feature

#43 Add "account_selection" Content Type Resolver
  Content/ContentTypeResolver/AccountSelectionResolver.php
  Resources/config/content-type-resolvers.xml
  Tests/Unit/Content/ContentTypeResolver/AccountSelectionResolverTest.php
Labels: Feature

#44 Add "contact_selection" Content Type Resolver
  Content/ContentTypeResolver/ContactSelectionResolver.php
  Resources/config/content-type-resolvers.xml
  Tests/Unit/Content/ContentTypeResolver/ContactSelectionResolverTest.php
Labels: Feature

#48 Fix regression in navigation response
  Content/Serializer/MediaSerializer.php
  Tests/Functional/Controller/responses/navigation__get_excerpt.json
Labels: bug

#47 Normalize view parameters for single and multi selection content types
  Content/ContentTypeResolver/AccountSelectionResolver.php
  Content/ContentTypeResolver/CategorySelectionResolver.php
  Content/ContentTypeResolver/ContactAccountSelectionResolver.php
  Content/ContentTypeResolver/ContactSelectionResolver.php
  Content/ContentTypeResolver/SingleAccountSelectionResolver.php
  Content/ContentTypeResolver/SingleCategorySelectionResolver.php
  Content/ContentTypeResolver/SingleContactSelectionResolver.php
  Tests/Unit/Content/ContentTypeResolver/AccountSelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/CategorySelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/ContactAccountSelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/ContactSelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/SingleAccountSelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/SingleCategorySelectionResolverTest.php
  Tests/Unit/Content/ContentTypeResolver/SingleContactSelectionResolverTest.php
  UPGRADE.md
Labels: DX

#13 Fix accessing of data in twig for meta twig extension
  Controller/HeadlessWebsiteController.php
  UPGRADE.md
Labels: DX
