Repository sulu/SuluHeadlessBundle, pull requests merged in 2020-11, with the labels that each got.

#55 Add defaults to propertyMap in PageSelectionResolver
  Content/ContentTypeResolver/ContactAccountSelectionResolver.php
  Content/ContentTypeResolver/PageSelectionResolver.php
  Content/DataProviderResolver/PageDataProviderResolver.php
  Tests/Unit/Content/ContentTypeResolver/PageSelectionResolverTest.php
  Tests/Unit/Content/DataProviderResolver/PageDataProviderResolverTest.php
Labels: DX

#56 Add single_snippet_selection content type resolver
  Content/ContentTypeResolver/SingleSnippetSelectionResolver.php
  Resources/config/content-type-resolvers.xml
  Tests/Unit/Content/ContentTypeResolver/SingleSnippetSelectionResolverTest.php
Labels: Feature

#58 Use MarkupParser to resolve sulu-link tags in TextEditorResolver
  Content/ContentTypeResolver/TextEditorResolver.php
  Resources/config/content-type-resolvers.xml
  Tests/Unit/Content/ContentTypeResolver/TextEditorResolverTest.php
Labels: bug
